export const FETCH_MATCH_LINES = "FETCH_MATCH_LINES"
export const RECEIVED_MATCH_LINES = "RECEIVED_MATCH_LINES"
export const FAILED_FETCH_MATCH_LINES = "FAILED_FETCH_MATCH_LINES"

export const FETCH_TOKEN = "FETCH_TOKEN"
export const RECEIVED_TOKEN = "RECEIVED_TOKEN"
export const FAILED_FETCH_TOKEN = "FAILED_FETCH_TOKEN"

export const FETCH_MATCH_DATA = "FETCH_MATCH_DATA"
export const RECEIVED_MATCH_DATA = "RECEIVED_MATCH_DATA"
export const FAILED_FETCH_MATCH_DATA = "FAILED_FETCH_MATCH_DATA"

export const FETCH_MATCH_MESSAGES = "FETCH_MATCH_MESSAGES"
export const RECEIVED_MATCH_MESSAGES = "RECEIVED_MATCH_MESSAGES"
export const FAILED_FETCH_MATCH_MESSAGES = "FAILED_FETCH_MATCH_MESSAGES"