export const FETCH_MATCH_LINES = "FETCH_MATCH_LINES"
export const RECEIVED_MATCH_LINES = "RECEIVED_MATCH_LINES"
export const FAILED_FETCH_MATCH_LINES = "FAILED_FETCH_MATCH_LINES"

export const FETCH_MATCHES = "FETCH_MATCHES"
export const RECEIVED_MATCHES = "RECEIVED_MATCHES"
export const FAILED_PENDING_MATCHES = "FAILED_PENDING_MATCHES"